apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: product
    varsion: 1.0.0
    environment: devlopment
  annotations:
    description: Ini adalah keterangan service
    description2: Ini adalah keterangan service 2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80